### ISSUE TITLE
Compression baselines 

### ISSUE THREAD

**Issue by alexanderpanchenko** [s-nlp/compression#1]
Use MOROCCO framework to test several baseline compression techniques.

Compression methods: 

Fetch feedforward layers of a Transformer model and apply to two matrices of this layer the following methods:

1) Weight pruning 
2) Weight quantisation
3) SVD (selecting optimal rank)
4) Optional: CP, and Tucker decompositions

**Baselines (optional):**

- Pruning of heads 

**Evaluation:** 

- Use MOROCCO script  
- Paper: https://arxiv.org/abs/2104.14314 
- Code: https://github.com/RussianNLP/MOROCCO 

**Models:**

Use models available in MOROCCO already that is 
- conversational ruBERT
- ruBERT (optional) 
- ruGPT (optional) 
- mBERT (optional) 

**Outcome:** 

- A table with metrics (cpu, memory, performance on tasks): original models vs compressed models 
- Similar to that in the MOROCCO table but with more models

**Comment by A1exRey** [comment]
done
